package チケット {
  interface チケット {
    ライブID
    グループID
    座席番号
  }
  class 余剰チケット {
  }
  class 割当て済みチケット {
    ユーザーID
    チケットID
  }
}

package アーティスト {
  class アーティスト {
    アーティストID
    アーティスト名
  }

}

package ライブ {
  class ツアー {
    ツアーID
    ツアー名
    ライブID
  }
  class ライブ<<RootEntity>> {
    ライブID
    アーティストID
    ライブタイトル
    開始日時
    終了日時
    会場
  }
}

package 会場 {
  class 会場 {
    会場名
    住所
  }
}

package グループ {
  class グループ {
    グループID
    ライブID
    グループ名
    公開・非公開
    + createdBy(ユーザーID)
    + メンバー追加()
  }
  class オーナー {
    ユーザーID
    グループID
  }
  class メンバー {
    ユーザーID
    グループID
  }
}

package ユーザー {
  class サインアップサービス<<Service>> {
    + signInWithTwitter()
  }
  class ユーザー {
    ユーザーID
    ユーザー名
    + 登録()
    + Twitter連携()
  }
}

package 評価 {
  class 評価 {
    評価ユーザーID
    評価対象ユーザーID
    評価内容
    + 評価する(評価ユーザーID, 評価対象ユーザーID)
  }
}

チケット -- ライブ
チケット <|-- 余剰チケット
チケット <|-- 割当て済みチケット
チケット -- グループ


アーティスト -- ライブ

グループ "1" o--"1..*" メンバー
グループ "1" o--"1..*" オーナー

メンバー --> ユーザー
オーナー --> ユーザー

ライブ "1" o-- "0..*" グループ
ライブ "1" o--"1" 会場

評価 -- ユーザー
